### ISSUE TITLE
Soulz

### ISSUE THREAD

**Issue by Reinified** [GangsterFox/AliuFox-themes#3]
hi, i dont know how to make a pull request so maybe you can review this and add onto themerdocu.

primary_dark_300 changes main chat buttons and setting icon colors. 
![primary_dark_300](https://user-images.githubusercontent.com/54984650/132083890-8c24b6eb-009b-4993-b9d8-1569df3fece3.jpg)

primary_dark_360 changes the channel and category text color and icons.
![look](https://user-images.githubusercontent.com/54984650/132084005-c7b35276-133d-4dd3-be57-34ba49ab3b4f.png)

drawable_overlay_channels_dark changes the channel color when holding town and/or tapping on it.  
https://user-images.githubusercontent.com/54984650/132084139-d121195f-0b41-4df9-80ee-b1c01acae0d0.mp4

ok

**Comment by GangsterFox** [comment]
Thanks for the issue, I will look through it doing tests and will add it to the docu once I am free. 
Have a good day

**Comment by GangsterFox** [comment]
hi! I have looked through all strings, all seem to work except for the last one overlay channels dark, it doesnt work on both the plugin or the xposed module.
Everything else has been tested and written on what it changes on the different versions and will be added to the docu shortly. Thanks for the help
